// Generate src/mermaid/seq_metrics_table.h from segoeui.ttf (fallback:
// OpenSans vendored). эмits a compact advance table for BMP range needed
// by the sequence engine's real-font sizing. Pure Node.
import { readFileSync, writeFileSync } from 'node:fs';

function parseTtf(buf) {
  const u16 = (o) => buf.readUInt16BE(o);
  const i16 = (o) => buf.readInt16BE(o);
  const tables = {};
  const n = u16(4);
  for (let i = 0; i < n; i++) {
    const off = 12 + i * 16;
    tables[buf.toString('latin1', off, off + 4)] = { offset: buf.readUInt32BE(off + 8) };
  }
  const upm = u16(tables['head'].offset + 18);
  const numH = u16(tables['hhea'].offset + 34);
  const hhea = tables['hhea'].offset;
  const asc = i16(hhea + 4), desc = i16(hhea + 6), gap = i16(hhea + 8);
  const hmtx = tables['hmtx'].offset;
  // select cmap
  const cmap = tables['cmap'].offset;
  const nSub = u16(cmap + 2);
  let sub = null, fmt = 0;
  for (let i = 0; i < nSub; i++) {
    const off = cmap + 4 + i * 8;
    const pid = u16(off), eid = u16(off + 2);
    const so = buf.readUInt32BE(off + 4);
    if ((pid === 3 && (eid === 1 || eid === 0)) || pid === 0) {
      const f = u16(cmap + so);
      if (f === 4 || f === 0) { sub = cmap + so; fmt = f; if (f === 4) break; }
    }
  }
  // default advance = last hmetric
  const advLast = u16(hmtx + (numH - 1) * 4);
  const adv = (g) => g >= numH ? advLast : u16(hmtx + g * 4);
  const glyph = (code) => {
    if (fmt === 4) {
      const segX2 = u16(sub + 6);
      const seg = segX2 / 2;
      const endO = sub + 14;
      const startO = endO + segX2 + 2;
      const deltaO = startO + segX2;
      const rangeO = deltaO + segX2;
      const c = code & 0xFFFF;
      for (let s = 0; s < seg; s++) {
        const end = u16(endO + s * 2);
        if (c <= end) {
          const start = u16(startO + s * 2);
          if (c >= start && c !== 0xFFFF) {
            const delta = i16(deltaO + s * 2);
            const range = u16(rangeO + s * 2);
            let g;
            if (range === 0) g = (c + delta) & 0xFFFF;
            else {
              const addr = rangeO + s * 2 + range + (c - start) * 2;
              const raw = u16(addr);
              g = raw === 0 ? 0 : (raw + delta) & 0xFFFF;
            }
            return g;
          }
          return 0;
        }
      }
      return 0;
    }
    return code < 256 ? buf[sub + 6 + code] : 0;
  };

  return { upm, numH, asc, desc, gap, adv, glyph };
}

// Which codepoints to emit: printable ASCII + Latin-1 + Danish specials +
// common punctuation/box-drawing used in sequence diagrams. Keep BMP-wise
// compact: emit codepoints 0x20-0x7E + 0xA0-0x17F + selected extras.
const cps = [];
for (let c = 0x20; c <= 0x7E; c++) cps.push(c);
for (let c = 0xA0; c <= 0x17F; c++) cps.push(c);
for (const c of [0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2013, 0x2014,
                 0x2026, 0x2192, 0x2190, 0x00D7, 0x2229, 0x00B7]) cps.push(c);

const WIN = '/mnt/c/Windows/Fonts/segoeui.ttf';
const FB = '/home/au19277/projekter/MarkDownIt/tools/mermaid-oracle/fonts/OpenSans-Regular.ttf';
let font;
try {
  font = parseTtf(readFileSync(WIN));
  console.log('using Segoe UI (segoeui.ttf)');
} catch {
  font = parseTtf(readFileSync(FB));
  console.log('Segoe UI not found (non-WSL?) — using vendored Open Sans');
}

const lines = [];
lines.push('// Generated by tools/mermaid-oracle/gen_seq_metrics.mjs — REAL font');
lines.push('// advances for the sequence engine (see gen header for font + metrics).');
lines.push('// Upm: ' + font.upm + '  line height@16: ' +
  ((font.asc - font.desc + font.gap) / font.upm * 16).toFixed(2));
lines.push('#pragma once');
lines.push('#include <cstdint>');
lines.push('namespace mermaid {');
lines.push('constexpr double kSeqFontUpm = ' + font.upm + '.0;');
lines.push('// Height: mermaid em-box round(size*1.332) — 21 @16px (pitch-52 verified).');
lines.push('constexpr double kSeqLineHeightPx16 = 21.0;');
lines.push('struct SeqAdvEntry { uint16_t cp; uint16_t adv; };');
lines.push('inline constexpr SeqAdvEntry kSeqAdv[] = {');
let rows = [];
for (const c of cps) {
  const g = font.glyph(c);
  const a = g ? font.adv(g) : font.adv(font.glyph(32));
  rows.push('  {0x' + c.toString(16).padStart(4, '0') + ',' + String(a).padStart(4) + '},');
}
lines.push(...rows);
lines.push('};');
lines.push('inline int kSeqAdvCount = ' + cps.length + ';');
lines.push('// lookup with linear+binary hybrid: table is sorted by cp');
lines.push('inline uint16_t SeqAdvanceFor(uint32_t cp) {');
lines.push('  int lo = 0, hi = kSeqAdvCount - 1;');
lines.push('  while (lo <= hi) {');
lines.push('    int mid = (lo + hi) / 2;');
lines.push('    if (kSeqAdv[mid].cp == cp) return kSeqAdv[mid].adv;');
lines.push('    if (kSeqAdv[mid].cp < cp) lo = mid + 1; else hi = mid - 1;');
lines.push('  }');
lines.push('  return 0;  // not in table: glyphs default to space advance at call site');
lines.push('}');
lines.push('}  // namespace mermaid');

const out = '/home/au19277/projekter/MarkDownIt/src/mermaid/seq_metrics_table.h';
writeFileSync(out, lines.join('\n') + '\n');
console.log('written', out, lines.length, 'lines /', cps.length, 'entries');
