
#pragma once

// Windows Ribbon Framework: COM classes and framework init/destroy.
// Based on the Microsoft SimpleRibbon sample.

#include <UIRibbon.h>
#include <UIRibbonPropertyHelpers.h>

// Command IDs generated by UICC from ribbon.xml.
// These must match the Id attributes in the XML markup.
#include "ribbonUI.h"

// Forward declaration: AppWindow provides callback methods.
class AppWindow;

// Ribbon framework globals (module-level).
extern IUIFramework* g_pRibbonFramework;
extern IUIApplication* g_pRibbonApplication;
extern UINT g_ribbonHeight;

// Initialize the Ribbon framework and attach it to the window.
bool InitRibbon(HWND hWnd, AppWindow* app);

// Destroy the Ribbon framework (release COM objects).
void DestroyRibbon();

// Notify the ribbon that the wrap toggle state changed.
// Called by AppWindow after toggling wrap mode.
void UpdateRibbonWrapState(bool wrapped);

class CRibbonApplication : public IUIApplication
{
public:
    static HRESULT CreateInstance(AppWindow* app, IUIApplication** ppApp);
    STDMETHOD_(ULONG, AddRef)();
    STDMETHOD_(ULONG, Release)();
    STDMETHOD(QueryInterface(REFIID iid, void** ppv));
    STDMETHOD(OnCreateUICommand)(UINT nCmdID, UI_COMMANDTYPE typeID, IUICommandHandler** ppCommandHandler);
    STDMETHOD(OnViewChanged)(UINT viewId, UI_VIEWTYPE typeId, IUnknown* pView, UI_VIEWVERB verb, INT uReasonCode);
    STDMETHOD(OnDestroyUICommand)(UINT32 commandId, UI_COMMANDTYPE typeID, IUICommandHandler* commandHandler);
private:
    CRibbonApplication(AppWindow* app) : m_cRef(1), m_pApp(app), m_pCommandHandler(NULL) {}
    ~CRibbonApplication();
    LONG m_cRef;
    AppWindow* m_pApp;
    IUICommandHandler* m_pCommandHandler;
};

class CRibbonCommandHandler : public IUICommandHandler
{
public:
    static HRESULT CreateInstance(AppWindow* app, IUICommandHandler** ppHandler);
    STDMETHOD_(ULONG, AddRef)();
    STDMETHOD_(ULONG, Release)();
    STDMETHOD(QueryInterface(REFIID iid, void** ppv));
    STDMETHOD(UpdateProperty)(UINT nCmdID, REFPROPERTYKEY key, const PROPVARIANT* ppropvarCurrentValue, PROPVARIANT* ppropvarNewValue);
    STDMETHOD(Execute)(UINT nCmdID, UI_EXECUTIONVERB verb, const PROPERTYKEY* key, const PROPVARIANT* ppropvarValue, IUISimplePropertySet* pCommandExecutionProperties);
private:
    CRibbonCommandHandler(AppWindow* app) : m_cRef(1), m_pApp(app) {}
    LONG m_cRef;
    AppWindow* m_pApp;
};
